---
name: Checks

on: [push]
jobs:
    test-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker
              uses: docker/setup-buildx-action@v3

      

            
            - name: Install Docker Compose
              run: |
                curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                chmod +x /usr/local/bin/docker-compose

            - name: Run tests
              run: docker compose run --rm app sh -c "python manage.py test"
